### ISSUE TITLE
Unable to connect - "Error: Time out"

### ISSUE THREAD

**Issue by ecwyne** [taskinen/tftp#1]
I haven't been able to set up a tftp server in docker. I'm publishing port 69, but every time I try my requests time out.

Am I missing anything?

**Comment by taskinen** [comment]
@ecwyne Are you sure you published the port in UDP mode? By default "-p 69:69" only exposes the port in TCP mode?

**Comment by ecwyne** [comment]
Here's my `docker-compose.yml`. When I test with my tftp client (I'm using [ntftp](https://www.npmjs.com/package/tftp#client_global)) the request times out
```yml
version: "3"
services:
    tftp:
        image: taskinen/tftp
        ports:
          - "69:69/udp"
        volumes:
          - ./apps/updater/build:/var/tftpboot:ro
        restart: unless-stopped
```
